PR-bugfix : getSeed expect an int and not a string
crash dump with
Error: Return value of pocketmine\level\Level::getSeed() must be of the type integer, string returned
File: /src/pocketmine/level/Level
Line: 2708