Fixed crash on unknown cause when killing a player
Part of crash dump:
PocketMine-MP Crash Dump Sat Apr 11 12:29:31 AZOST 2015

Error: Call to a member function getCause() on null
File: /src/pocketmine/Player
Line: 2581
Type: E_ERROR

Code:
[2572] 
[2573] 		$message = "death.attack.generic";
[2574] 
[2575] 		$params = [
[2576] 			$this->getName()
[2577] 		];
[2578] 
[2579] 		$cause = $this->getLastDamageCause();
[2580] 
[2581] 		switch($cause->getCause()){
[2582] 			case EntityDamageEvent::CAUSE_ENTITY_ATTACK:
[2583] 				if($cause instanceof EntityDamageByEntityEvent){
[2584] 					$e = $cause->getDamager();
[2585] 					if($e instanceof Player){
[2586] 						$message = "death.attack.player";
[2587] 						$params[] = $e->getName();
[2588] 						break;
[2589] 					}elseif($e instanceof Living){
[2590] 						$message = "death.attack.mob";
[2591] 						$params[] = $e->getName();

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1010 [Protocol 21; API 1.12.0]